### ISSUE TITLE
LEDs flickers on ESP32

### ISSUE THREAD

**Issue by RootShell-coder** [ElizabethMorves/little-house-sings#5]
On ESP32 LEDs flash randomly. I installed a resistor on the data bus and installed an additional capacitor for power supply. The Oscilloscope shows every 1 millisecond a data packet which knocks down randomly the glow of the LED in the strip. On esp8266 this effect is not observed.

thanks

**Comment by ElizabethMorves** [comment]
This problem is in the library Adafruit NeoPixel issues [#177](https://github.com/kitesurfer1404/WS2812FX/issues/177#issue-433422411).
As an alternative to the timing sensitive "bit-bang" technique, the ESP32's [RMT](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/rmt.html) hardware can be used to drive the LEDs. Looks like one should use [RMT driver](https://github.com/kitesurfer1404/WS2812FX/tree/master/examples/ws2812fx_esp32) for ESP32.

**Comment by ElizabethMorves** [comment]
Сheck this code on esp8266
